name: .NET

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    permissions:
      contents: read
      packages: write

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: dotnet pack --configuration Release -p:PackageVersion=1.0.${{github.run_number}}
    - name: Publish to GitHub Packages
      if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
      run: |
        dotnet nuget add source --username ledgerscope --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/ledgerscope/index.json"
        dotnet nuget push "R4MVC/R4MVC/src/R4Mvc.Tools/bin/Release/R4Mvc.Tools.*.nupkg" --source "github" --api-key ${{ secrets.GITHUB_TOKEN }}
